### ISSUE TITLE
Decide on frontend frameworks to use

### ISSUE THREAD

**Issue by elkowar** [bazed-editor/bazed#5]
We need to do further evaluation if our current choice of tauri + Svelte is feasible, especially w.r.t. the performance and rendering issues we noticed in tauri.

**Comment by rice7th** [comment]
I've recently seen many useful options. Here are some:

- [KAS](https://github.com/kas-gui/kas): Very interesting gui lib that is in it's early stages.
- [Iced](https://github.com/iced-rs/iced): Very popular and very expandible gui lib. Used by System76 in their newest COSMIC desktop
- [Egui](https://github.com/emilk/egui): One of the most powerful gui libs. It is immediate mode tho.
- [Druid](https://github.com/linebender/druid): Very mature gui lib yet no support for GPU
- [Tauri](https://github.com/tauri-apps/tauri): Rusty electron
- Custom: Something like Skia, Blender's GUI or more in general a renderer built on top of low level crates (like `wgpu`). Text rendering may be provided by COSMIC Text since it is the most accurate one yet.

**Comment by elkowar** [comment]
So far it does look like where gonna go with Tauri + Svelte, although Tauri seemed slliiiiightly sketchy in our first tests... We'll need to see. Going native would be nice, but also _very_ high complexity in comparison, possibly

**Comment by druskus20** [comment]
Seems like we are indeed going for tauri + svelte so I'll close this for the meantime
